#%RAML 1.0 SecurityScheme
type: Basic Authentication 
describedBy:
  headers:
    username:
      type: string
      required: true
    password:
      type: string
      required: true
  responses:
    400:
      body:
        application/json:
          type: object
          example: {
             status: "bad request"
            }
