#%RAML 1.0 SecurityScheme
type: x-client-enforcement
describedBy:
  headers:
    client_id:
      type: string
      required: true
      maxLength: 10
      minLength: 2
      example: "23d"
    client_secret:
      type: string
      required: true
      maxLength: 10
      minLength: 3
      example: "3hr8"
  responses:
    401:
      body:
        application/json:          
          example:
            {
              "error": "unauthorized details"
            }
               

            
            
