#%RAML 1.0 DataType
properties:
  albumID:
    type: string
    example: "I23"
  songID:
    type: array
    example: [34,67,22]
  yearRealeased:
    type: number
    example: 2018
  artistName:
    type: string[]
    example: ["alec benjamin", "Justin Bieber"]