#%RAML 1.0 DataType
properties:
  artistName:
    type: string[]
    example: ["alec benjamin", "Selena Gomez", "Taylor Swift"]
  artistID:
    type: number
    example: 12
  albumID:
    type: string
    example: "I23"
  artist-birthdate:
    type: number
    example: 1994