#%RAML 1.0 DataType
properties:
  songName: 
    type: string
    example: "Let me down slowly" 
  songID: 
    type: array
    example: [34] 
  duration: 
    type: string
    example: "2.58 min" 
  yearReleased: 
    type: number
    example: 2018 

